// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs3eN4qVuBh0pEUsj5hFlw1GFro2_aYFM',
    appId: '1:501162357732:web:5ad86dceb3950474be0df1',
    messagingSenderId: '501162357732',
    projectId: 'test-f2a12',
    authDomain: 'test-f2a12.firebaseapp.com',
    storageBucket: 'test-f2a12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrndvJq0UpPinuPcBskG6u2-zvOJh3SF8',
    appId: '1:501162357732:android:4b181e2dcb0167fbbe0df1',
    messagingSenderId: '501162357732',
    projectId: 'test-f2a12',
    storageBucket: 'test-f2a12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZyYTnX8UHErQtABD9NuLXDEXOTkewhxo',
    appId: '1:501162357732:ios:3e15fab5faf9e477be0df1',
    messagingSenderId: '501162357732',
    projectId: 'test-f2a12',
    storageBucket: 'test-f2a12.appspot.com',
    iosClientId: '501162357732-esd7jen1a6l3l9hsbp4g2bhmap2sfjdk.apps.googleusercontent.com',
    iosBundleId: 'com.zainon.socketPushNotifictions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZyYTnX8UHErQtABD9NuLXDEXOTkewhxo',
    appId: '1:501162357732:ios:3e15fab5faf9e477be0df1',
    messagingSenderId: '501162357732',
    projectId: 'test-f2a12',
    storageBucket: 'test-f2a12.appspot.com',
    iosClientId: '501162357732-esd7jen1a6l3l9hsbp4g2bhmap2sfjdk.apps.googleusercontent.com',
    iosBundleId: 'com.zainon.socketPushNotifictions',
  );
}
